### ISSUE TITLE
npm WARN deprecated files/libraries?

### ISSUE THREAD

**Issue by NylaTheWolf** [moom0o/UnlistedVideosScraper#1]
I tried running npm install inside the folder for the Unlisted Video Scraper, and I got these messages:
![Screen Shot 2021-06-23 at 11 26 22 PM](https://user-images.githubusercontent.com/41797151/123198353-f1a2a980-d47a-11eb-95e6-427fbe081655.png)

Is this something to be worried about? What should I do?

Edit: I tried to proceed with `node index.js` and I got an Error 503 response
![Screen Shot 2021-06-23 at 11 32 35 PM](https://user-images.githubusercontent.com/41797151/123198612-6aa20100-d47b-11eb-8b0a-5f3956a69be0.png)

**Comment by moom0o** [comment]
1) Probably not, you can ignore it
2) Edit the cookie header in index.js with your cloudflare clearance. I updated README with better instructions.

**Comment by NylaTheWolf** [comment]
> 1. Probably not, you can ignore it
> 2. Edit the cookie header in index.js with your cloudflare clearance. I updated README with better instructions.

Er, what if I'm on Mac? hitting fn+f12 doesn't do anything.

**Comment by moom0o** [comment]
> > 1. Probably not, you can ignore it
> > 2. Edit the cookie header in index.js with your cloudflare clearance. I updated README with better instructions.
> 
> Er, what if I'm on Mac? hitting fn+f12 doesn't do anything.

Right click inspect element. Alternatively you can just use links.txt where I already ran it myself.
https://github.com/moom0o/UnlistedVideosScraper/blob/master/links.txt
